### ISSUE TITLE
Add Badger to KV DB list

### ISSUE THREAD

**Issue by corporatepiyush** [gostor/awesome-go-storage#14]

**Comment by carmark** [comment]
hello @corporatepiyush ,

Do you mean this [badger](https://github.com/dgraph-io/badger)? would you like to submit a PR to do that?

Thanks,
-Lei

**Comment by funny-falcon** [comment]
Yes, that badger.

**Comment by carmark** [comment]
@corporatepiyush This PR https://github.com/gostor/awesome-go-storage/pull/9/ has been merged, thanks.
