### ISSUE TITLE
Add Consul?

### ISSUE THREAD

**Issue by mark-i-m** [gostor/awesome-go-storage#3]
Have you considered adding [hashicorp/consul](https://github.com/hashicorp/consul) under KV stores? Really, it's fundamentally a Paxos lock service, but it exposes that as a storage service.

**Comment by carmark** [comment]
Yeah, that should be reasonable. Would you like to submit a PR to do that? @mark-i-m

**Comment by mark-i-m** [comment]
Done :smile: 

#7
