### ISSUE TITLE
Inaccurate description of go-mssqldb 

### ISSUE THREAD

**Issue by mikewilliamson** [gostor/awesome-go-storage#4]
I think it's rather unfair to refer to go-mssqldb as a "prototype".  It is a mature, robust, pure Go implementation of the TDS protocol, with various extensions to support features specific to MS SQL Server.  I've used it in mission-critical, production systems doing millions of transactions per day.  I don't see why the term "prototype" would be more applicable to it than to any other Go database driver.

**Comment by carmark** [comment]
fixed by https://github.com/gostor/awesome-go-storage/commit/acb75cd5a398263f13cd3248949960063ae44fc9. Thanks.
